version: '3'
services: 
  postgres:
    image: postgres:9.6.23-buster
    env_file: ./.env
    environment: 
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports: 
      - "5432:5432"
  
  app: 
    build: .
    env_file: ./.env
    environment: 
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: communication
    ports: 
      - "5000:5000"
    depends_on: 
      - postgres
    restart: on-failure # will restart until it's success